#!/bin/sh
curl -f -L -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip 2>/dev/null || \
curl -f -s http://169.254.169.254/metadata/v1/interfaces/public/0/ipv4/address
